#!/bin/bash
#

usage() {
	echo Usage: yhname user [id] [username]
	echo Usage: yhname deluser [username]
	echo Usage: yhname sacct [username]

}


if [[ -z "$1" ]];then
	usage
	exit 1
elif  (($1==delu && $#==1));then
	echo 
elif  (($1==user&& $#==3));then
	echo create user;
elif (($1==sacct&&$#==2));then
	echo 
else 
	usage
	exit 1
fi


case $1 in
user)
	node=`scontrol show hostname cn[0-10],cn12,cn[14-15],mn0`
	for i in $node
	do
		echo ==================== $i ===========================
		ssh $i "groupadd -g $2 $3;useradd -u $2 -g  $3 -d /gfdata/home/$3 -m -s /bin/bash $3 >/dev/null 2>&1;echo $3:123456 |chpasswd" 
	done
	;;

deluser)
	node=`scontrol show hostname cn[0-10],cn12,cn[14-15],mn0`
	for i in $node
        do
                echo ==================== $i ===========================
                ssh $i "userdel $2"
        done
        ;;


sacct)
	#username  = grep -w $2 /etc/passwd
	if grep -w $2 /etc/passwd  >/dev/null 2>&1;then
		echo start authorization !
	else
		echo $2 does not exist, Please create username!!
		exit 0
	fi
	sacctmgr add account name=$2 cluster=yhstar
	sacctmgr add user name=$2 account=$2
	echo $2 authorization successful !
	;;
*)
	usage
	;;
esac

exit $?
    
